version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y portaudio19-dev
      pip install -r requirements.txt
    startCommand: python message.py
    ports:
      - 80
